[tools]
# ansible = "latest"
fnox = "1.19.0"

[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"

[env]
_.fnox-env = { tools = true }

[tasks.run]
description = "Run Ansible playbook"
dir = "ansible"
shell = "bash -c"
run = """
set -euxo pipefail
if [ ! -f /tmp/ansible-openwrt.log ]; then
  ansible-playbook --diff main.yml -i inventory/hosts 2>&1 | tee /tmp/ansible-openwrt.log
else
  ansible-playbook --diff main.yml -i inventory/hosts
fi
"""
