- name: Configure system
  ansible.builtin.template:
    dest: /etc/config/system
    src: files/{{ inventory_hostname }}/etc/config/system.j2
    mode: u=rw,g=,o=
    backup: true

- name: Create dropbear_ed25519_host_key for dropbear
  ansible.builtin.shell: |
    python3 - <<'PY'
    import base64, pathlib
    data = base64.b64decode("{{ dropbear_ed25519_host_key }}")
    pathlib.Path("/etc/dropbear/dropbear_ed25519_host_key").write_bytes(data)
    PY
  changed_when: false
  no_log: true

- name: Create authorized_keys for dropbear (/etc/dropbear/authorized_keys)
  ansible.builtin.copy:
    dest: /etc/dropbear/authorized_keys
    src: files/{{ inventory_hostname }}/etc/dropbear/authorized_keys
    mode: u=rw,g=,o=
    backup: true

- name: Configure networks
  ansible.builtin.template:
    dest: /etc/config/network
    src: files/{{ inventory_hostname }}/etc/config/network.j2
    mode: u=rw,g=,o=
    backup: true

- name: Configure Firewall
  ansible.builtin.template:
    dest: /etc/config/firewall
    src: files/{{ inventory_hostname }}/etc/config/firewall.j2
    mode: u=rw,g=r,o=r
    backup: true

- name: Configure WiFi
  ansible.builtin.template:
    dest: /etc/config/wireless
    src: files/{{ inventory_hostname }}/etc/config/wireless.j2
    mode: u=rw,g=r,o=r
    backup: true
  no_log: true

- name: Set root password
  ansible.builtin.replace:
    path: /etc/shadow
    regexp: "^root:([^:]*):"
    replace: "root:{{ root_password | string | password_hash('sha256') }}:"
    backup: true
  changed_when: false

- name: Install packages
  community.general.apk:
    name: "{{ openwrt_packages | join(',') }}"

- name: Configure DHCP
  ansible.builtin.template:
    dest: /etc/config/dhcp
    src: files/{{ inventory_hostname }}/etc/config/dhcp.j2
    mode: u=rw,g=,o=
    backup: true

- name: Change root shell to /bin/bash
  ansible.builtin.replace:
    path: /etc/passwd
    regexp: "^root:(.*):/bin/ash"
    replace: "root:\\1:/bin/bash"
    backup: true

- name: Add nice prompt for root user
  ansible.builtin.blockinfile:
    dest: /etc/profile
    backup: true
    block: |
      ps1_prompt() {
          local ps1_exit=$?

          if [ $ps1_exit -eq 0 ]; then
              ps1_status='\$'
          else
              ps1_status=`echo -e "\[\\033[1;31m\]"'\\\$'"\[\\033[00m\]"`
          fi

          PS1="\[\\033[01;31m\]\u@\h\[\\033[00m\]:\[\\033[01;34m\]\w${ps1_status} \[\\033[00m\]"
      }

      PROMPT_COMMAND="ps1_prompt;$PROMPT_COMMAND"

- name: Create /etc/profile.d directory
  ansible.builtin.file:
    path: /etc/profile.d
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Get the history format file (/etc/profile.d/history_format.sh)
  ansible.builtin.copy:
    dest: /etc/profile.d/history_format.sh
    mode: u=rw,g=r,o=r
    backup: true
    content: |
      HISTTIMEFORMAT="|%F %R| "

- name: Configure vnstat (/etc/config/vnstat)
  ansible.builtin.template:
    dest: /etc/config/vnstat
    src: files/{{ inventory_hostname }}/etc/config/vnstat.j2
    mode: u=rw,g=,o=
    backup: true

- name: Luci statistics (/etc/config/luci_statistics)
  ansible.builtin.template:
    dest: /etc/config/luci_statistics
    src: files/{{ inventory_hostname }}/etc/config/luci_statistics.j2
    mode: u=rw,g=r,o=r
    backup: true

- name: Configure uhttpd (Use HTTPS for LuCI)
  ansible.builtin.copy:
    dest: /etc/config/uhttpd
    src: files/{{ inventory_hostname }}/etc/config/uhttpd
    mode: u=rw,g=,o=
    backup: true

- name: Create directory for mc inside ~/.config
  ansible.builtin.file:
    path: ~/.config/mc/
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create MC config file
  ansible.builtin.copy:
    dest: ~/.config/mc/ini
    mode: u=rw,g=r,o=r
    backup: true
    content: |
      [Midnight-Commander]
      auto_save_setup=0
      drop_menus=1
      use_internal_edit=1
      confirm_exit=0
      editor_return_does_auto_indent=0

      [Layout]
      keybar_visible=0
      menubar_visible=0
      message_visible=0

      [Panels]
      navigate_with_arrows=1

- name: Configure MC to run without mouse (/etc/profile.d/my-mc.sh)
  ansible.builtin.copy:
    dest: /etc/profile.d/my-mc.sh
    mode: u=rwx,g=rx,o=rx
    backup: true
    content: |
      #!/usr/bin/env sh

      # Don't define aliases in plain Bourne shell
      [ -n "${BASH_VERSION}${KSH_VERSION}${ZSH_VERSION}" ] || return 0
      alias mc='/usr/bin/mc --nomouse'

- name: Configure banip
  ansible.builtin.copy:
    dest: /etc/config/banip
    src: files/{{ inventory_hostname }}/etc/config/banip
    mode: u=rw,g=,o=
    backup: true

############################################
# Configure msmtp + email notifications
############################################

- name: Configure msmtp
  ansible.builtin.template:
    dest: /etc/msmtprc
    src: files/etc/msmtprc.j2
    mode: u=rw,g=,o=
    backup: true
  no_log: true

- name: Reboot notification
  ansible.builtin.template:
    dest: /etc/rc.local
    src: files/etc/rc.local.j2
    mode: u=rwx,g=rx,o=rx
    backup: true

############################################
# USB disk
############################################
- name: Configure USB disk if defined
  when: openwrt_backup_directory is defined and usb_disk_device is defined
  block:
    - name: Configure attached block device {{ usb_disk_device }}
      ansible.builtin.template:
        dest: /etc/config/fstab
        src: files/{{ inventory_hostname }}/etc/config/fstab.j2
        mode: u=rw,g=r,o=r
        backup: true

    - name: Create directory {{ usb_disk_mount_path }}
      ansible.builtin.file:
        path: "{{ usb_disk_mount_path }}"
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: Check the mounted disks
      ansible.builtin.command: |
        cat /proc/mounts
      changed_when: false
      register: mount_output

    - name: Create file usb_disk_mount_path/USB_DISK_NOT_PRESENT if usb_disk_device_1 is not mounted
      ansible.builtin.copy:
        dest: "{{ usb_disk_mount_path }}/USB_DISK_NOT_PRESENT"
        content: ""
        force: false
        mode: u=rw,g=r,o=r
      when: mount_output.stdout is not search('/dev/' + usb_disk_device + '1 ' + usb_disk_mount_path )

    - name: Create "media" directories on the disk
      ansible.builtin.file:
        path: "{{ usb_disk_mount_path }}/{{ item.name }}"
        state: directory
        owner: root
        group: root
        mode: "{{ item.mode | default('u=rwx,g=rx,o=rx') }}"
      loop:
        - name: media
          mode: u=rx,g=rx,o=rx
        - name: media/movies
        - name: media/music

    - name: Mount USB disk
      ansible.builtin.command: |
        /sbin/block mount
      register: block_mount
      changed_when: block_mount.stdout is not search('/dev/' + usb_disk_device + '1 is already mounted')
      when: mount_output.stdout is not search('/dev/' + usb_disk_device + '1 ' + usb_disk_mount_path )
  rescue:
    - name: Print when errors
      ansible.builtin.fail:
        msg: Restore from backup failed

############################################
# Add backup script
############################################
- name: Create backup directory
  ansible.builtin.file:
    path: "{{ openwrt_backup_directory }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Copy the backup script collectd_nlbwmon_vnstat-backup to /etc/init.d/
  ansible.builtin.template:
    dest: /etc/init.d/collectd_nlbwmon_vnstat-backup
    src: files/etc/init.d/collectd_nlbwmon_vnstat-backup.j2
    mode: u=rwx,g=rx,o=rx
    backup: true
  notify: Enable collectd_nlbwmon_vnstat-backup on boot + restore data from backup

- name: Configure to run collectd_nlbwmon_vnstat-backup daily
  ansible.builtin.cron:
    name: "Backup collectd nlbwmon vnstat databases"
    minute: "0"
    hour: "3"
    job: "/etc/init.d/collectd_nlbwmon_vnstat-backup backup"

- name: Restore data using collectd_nlbwmon_vnstat-backup
  ansible.builtin.command: /etc/init.d/collectd_nlbwmon_vnstat-backup restore
  args:
    creates: /tmp/rrd/{{ inventory_hostname_short }}/cpu-0
