- name: Install Python
  ansible.builtin.raw: test -e /usr/bin/python3 || ( apk add python3-light python3-decimal python3-idna python3-logging )
  changed_when: false

- name: Configure system
  ansible.builtin.template:
    dest: /etc/config/system
    src: files/{{ inventory_hostname }}/etc/config/system.j2
    mode: u=rw,g=,o=

- name: Create dropbear_*_host_key for dropbear
  shell: |
    python3 - <<'PY'
    import base64, pathlib
    data = base64.b64decode("{{ item.content }}")
    pathlib.Path("{{ item.file }}").write_bytes(data)
    PY
  loop:
    - file: /etc/dropbear/dropbear_ed25519_host_key
      content: "{{ dropbear_ed25519_host_key }}"
    - file: /etc/dropbear/dropbear_rsa_host_key
      content: "{{ dropbear_rsa_host_key }}"
  changed_when: false
  no_log: true

- name: Create authorized_keys for dropbear (/etc/dropbear/authorized_keys)
  ansible.builtin.template:
    dest: /etc/dropbear/authorized_keys
    src: files/etc/dropbear/authorized_keys.j2
    mode: u=rw,g=,o=

- name: Configure networks
  ansible.builtin.template:
    dest: /etc/config/network
    src: files/{{ inventory_hostname }}/etc/config/network.j2
    mode: u=rw,g=,o=

- name: Configure Firewall
  ansible.builtin.copy:
    dest: /etc/config/firewall
    src: files/{{ inventory_hostname }}/etc/config/firewall
    mode: u=rw,g=r,o=r

- name: Configure WiFi
  ansible.builtin.template:
    dest: /etc/config/wireless
    src: files/{{ inventory_hostname }}/etc/config/wireless.j2
    mode: u=rw,g=r,o=r
  no_log: true

- name: Set root password
  ansible.builtin.replace:
    path: /etc/shadow
    regexp: "^root:([^:]*):"
    replace: "root:{{ root_password | string | password_hash('sha256') }}:"
  changed_when: false

- name: Install packages
  community.general.apk:
    name: "{{ openwrt_packages | join(',') }}"

- name: Configure DHCP
  ansible.builtin.template:
    dest: /etc/config/dhcp
    src: files/{{ inventory_hostname }}/etc/config/dhcp.j2
    mode: u=rw,g=,o=

- name: Change root shell to /bin/bash
  ansible.builtin.replace:
    path: /etc/passwd
    regexp: "^root:(.*):/bin/ash"
    replace: "root:\\1:/bin/bash"

- name: Add nice prompt for root user
  ansible.builtin.blockinfile:
    dest: /etc/profile
    block: |
      ps1_prompt() {
          local ps1_exit=$?

          if [ $ps1_exit -eq 0 ]; then
              ps1_status='\$'
          else
              ps1_status=`echo -e "\[\\033[1;31m\]"'\\\$'"\[\\033[00m\]"`
          fi

          PS1="\[\\033[01;31m\]\u@\h\[\\033[00m\]:\[\\033[01;34m\]\w${ps1_status} \[\\033[00m\]"
      }

      PROMPT_COMMAND="ps1_prompt;$PROMPT_COMMAND"

- name: Create /etc/profile.d directory
  ansible.builtin.file:
    path: /etc/profile.d
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Get the history format file (/etc/profile.d/history_format.sh)
  ansible.builtin.copy:
    dest: /etc/profile.d/history_format.sh
    mode: u=rw,g=r,o=r
    content: |
      HISTTIMEFORMAT="|%F %R| "

- name: Configure vnstat (/etc/config/vnstat)
  ansible.builtin.template:
    dest: /etc/config/vnstat
    src: files/{{ inventory_hostname }}/etc/config/vnstat.j2
    mode: u=rw,g=,o=

- name: Luci statistics (/etc/config/luci_statistics)
  ansible.builtin.template:
    dest: /etc/config/luci_statistics
    src: files/{{ inventory_hostname }}/etc/config/luci_statistics.j2
    mode: u=rw,g=r,o=r

- name: Configure uhttpd (Use HTTPS for LuCI)
  ansible.builtin.copy:
    dest: /etc/config/uhttpd
    src: files/{{ inventory_hostname }}/etc/config/uhttpd
    mode: u=rw,g=,o=

- name: Create directory for mc inside ~/.config
  ansible.builtin.file:
    path: ~/.config/mc/
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Create MC config file
  ansible.builtin.copy:
    dest: ~/.config/mc/ini
    mode: u=rw,g=r,o=r
    content: |
      [Midnight-Commander]
      auto_save_setup=0
      drop_menus=1
      use_internal_edit=1
      confirm_exit=0
      editor_return_does_auto_indent=0

      [Layout]
      keybar_visible=0
      menubar_visible=0
      message_visible=0

      [Panels]
      navigate_with_arrows=1

- name: Configure MC to run without mouse (/etc/profile.d/my-mc.sh)
  ansible.builtin.copy:
    dest: /etc/profile.d/my-mc.sh
    mode: u=rwx,g=rx,o=rx
    content: |
      #!/usr/bin/env sh

      # Don't define aliases in plain Bourne shell
      [ -n "${BASH_VERSION}${KSH_VERSION}${ZSH_VERSION}" ] || return 0
      alias mc='/usr/bin/mc --nomouse'

- name: Configure banip
  ansible.builtin.copy:
    dest: /etc/config/banip
    src: files/{{ inventory_hostname }}/etc/config/banip
    mode: u=rw,g=,o=

############################################
# Configure msmtp + email notifications
############################################

- name: Configure msmtp
  ansible.builtin.template:
    dest: /etc/msmtprc
    src: files/etc/msmtprc.j2
    mode: u=rw,g=,o=
  no_log: true

- name: Reboot notification
  ansible.builtin.template:
    dest: /etc/rc.local
    src: files/etc/rc.local.j2
    mode: u=rwx,g=rx,o=rx
