- name: Configure alerting for dnsmasq (notify when there is new MAC on the network)
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    line: "dhcp-script=/etc/dnsmasq-script.sh"

- name: Copy the dnsmasq-script.sh to /etc/
  ansible.builtin.template:
    dest: /etc/dnsmasq-script.sh
    src: files/{{ inventory_hostname }}/etc/dnsmasq-script.sh.j2
    mode: u=rwx,g=rx,o=rx

- name: Configure ddns
  ansible.builtin.template:
    dest: /etc/config/ddns
    src: files/{{ inventory_hostname }}/etc/config/ddns.j2
    mode: u=rw,g=r,o=r

- name: Configure OpenVPN (/etc/config/openvpn)
  ansible.builtin.copy:
    dest: /etc/config/openvpn
    src: files/{{ inventory_hostname }}/etc/config/openvpn
    mode: u=rw,g=r,o=r

- name: Put OpenVPN VPS Free configuration to /etc/openvpn/
  ansible.builtin.copy:
    dest: /etc/openvpn/ipv6tun-petrruzicka1.ovpn
    src: files/{{ inventory_hostname }}/etc/openvpn/ipv6tun-petrruzicka1.ovpn
    mode: u=rw,g=,o=
