- name: Configure hd-idle
  ansible.builtin.copy:
    dest: /etc/config/hd-idle
    src: files/{{ inventory_hostname }}/etc/config/hd-idle
    mode: u=rw,g=,o=
    backup: true

- name: Configure prometheus-node-exporter-ucode
  ansible.builtin.copy:
    dest: /etc/config/prometheus-node-exporter-ucode
    src: files/{{ inventory_hostname }}/etc/config/prometheus-node-exporter-ucode
    mode: u=rw,g=,o=
    backup: true

- name: Configure cloudflared
  ansible.builtin.template:
    dest: /etc/config/cloudflared
    src: files/{{ inventory_hostname }}/etc/config/cloudflared.j2
    mode: u=rw,g=,o=
    backup: true
  no_log: true

############################################
# Transmission
############################################
- name: Configure transmission
  ansible.builtin.template:
    dest: /etc/config/transmission
    src: files/{{ inventory_hostname }}/etc/config/transmission.j2
    mode: u=rw,g=r,o=r
    backup: true

- name: Start transmission
  community.general.openwrt_init:
    name: transmission
    state: started
    enabled: true

- name: Download block list
  ansible.builtin.command: wget "{{ transmission_blocklist_url }}" -O "{{ usb_disk_mount_path }}/torrents/config/blocklists/bt_blocklists"
  args:
    creates: "{{ usb_disk_mount_path }}/torrents/config/blocklists/bt_blocklists"

- name: Set proper permissions for block list
  ansible.builtin.file:
    path: "{{ usb_disk_mount_path }}/torrents/config/blocklists/bt_blocklists"
    owner: transmission
    group: transmission
    mode: u=rw,g=r,o=r

- name: Create Luci ACL for Homepage OpenWRT widget
  ansible.builtin.copy:
    dest: /usr/share/rpcd/acl.d/homepage.json
    src: files/{{ inventory_hostname }}/usr/share/rpcd/acl.d/homepage.json
    mode: u=rw,g=r,o=r
    backup: true

- name: Allow Homepage OpenWRT widget to access Luci via RPC
  ansible.builtin.template:
    dest: /etc/config/rpcd
    src: files/{{ inventory_hostname }}/etc/config/rpcd.j2
    mode: u=rw,g=r,o=r
    backup: true
  no_log: true

- name: Configure samba4
  ansible.builtin.template:
    dest: /etc/config/samba4
    src: files/{{ inventory_hostname }}/etc/config/samba4.j2
    mode: u=rw,g=,o=
    backup: true
