############################################
# USB disk
############################################
- name: Configure USB disk if defined
  when: openwrt_backup_directory is defined and usb_disk_device is defined
  block:
    - name: Configure attached block device {{ usb_disk_device }}
      ansible.builtin.template:
        dest: /etc/config/fstab
        src: files/{{ inventory_hostname }}/etc/config/fstab.j2
        mode: u=rw,g=r,o=r

    - name: Create directory {{ usb_disk_mount_path }}
      ansible.builtin.file:
        path: "{{ usb_disk_mount_path }}"
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: Check the mounted disks
      ansible.builtin.command: |
        cat /proc/mounts
      changed_when: false
      register: mount_output

    - name: Create file usb_disk_mount_path/USB_DISK_NOT_PRESENT if usb_disk_device_1 is not mounted
      ansible.builtin.file:
        path: "{{ usb_disk_mount_path }}/USB_DISK_NOT_PRESENT"
        state: touch
        mode: u=rw,g=r,o=r
      when: mount_output.stdout is not search('/dev/' + usb_disk_device + '1 ' + usb_disk_mount_path )

    - name: Create "media" directories on the disk
      ansible.builtin.file:
        path: "{{ usb_disk_mount_path }}/{{ item.name }}"
        state: directory
        owner: root
        group: root
        mode: "{{ item.mode | default('u=rwx,g=rx,o=rx') }}"
      loop:
        - name: media
          mode: u=rx,g=rx,o=rx
        - name: media/movies
        - name: media/music

    - name: Mount USB disk
      ansible.builtin.command: |
        /sbin/block mount
      register: block_mount
      changed_when: block_mount.stdout is not search('/dev/' + usb_disk_device + '1 is already mounted')
      when: mount_output.stdout is not search('/dev/' + usb_disk_device + '1 ' + usb_disk_mount_path )

    - name: Configure hd-idle
      ansible.builtin.copy:
        dest: /etc/config/hd-idle
        src: files/{{ inventory_hostname }}/etc/config/hd-idle
        mode: u=rw,g=,o=
  rescue:
    - name: Print when errors
      ansible.builtin.fail:
        msg: Restore from backup failed

############################################
# Add backup script
############################################
- name: Create backup directory
  ansible.builtin.file:
    path: "{{ openwrt_backup_directory }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Copy the backup script collectd_nlbwmon_vnstat-backup to /etc/init.d/
  ansible.builtin.template:
    dest: /etc/init.d/collectd_nlbwmon_vnstat-backup
    src: files/etc/init.d/collectd_nlbwmon_vnstat-backup.j2
    mode: u=rwx,g=rx,o=rx
  notify: Enable collectd_nlbwmon_vnstat-backup on boot + restore data from backup

- name: Configure to run collectd_nlbwmon_vnstat-backup daily
  ansible.builtin.cron:
    name: "Backup collectd nlbwmon vnstat databases"
    minute: "0"
    hour: "3"
    job: "/etc/init.d/collectd_nlbwmon_vnstat-backup backup"

- name: Restore data using collectd_nlbwmon_vnstat-backup
  ansible.builtin.command: /etc/init.d/collectd_nlbwmon_vnstat-backup restore
  args:
    creates: /tmp/rrd/{{ inventory_hostname_short }}/cpu-0

- name: Configure prometheus-node-exporter-ucode
  ansible.builtin.copy:
    dest: /etc/config/prometheus-node-exporter-ucode
    src: files/{{ inventory_hostname }}/etc/config/prometheus-node-exporter-ucode
    mode: u=rw,g=,o=

- name: Configure cloudflared
  ansible.builtin.template:
    dest: /etc/config/cloudflared
    src: files/{{ inventory_hostname }}/etc/config/cloudflared.j2
    mode: u=rw,g=,o=

############################################
# Transmission
############################################

- name: Configure transmission
  ansible.builtin.template:
    dest: /etc/config/transmission
    src: files/{{ inventory_hostname }}/etc/config/transmission.j2
    mode: u=rw,g=r,o=r

- name: Start transmission
  community.general.openwrt_init:
    name: transmission
    state: started
    enabled: true

- name: Download block list
  ansible.builtin.command: wget "{{ transmission_blocklist_url }}" -O "{{ usb_disk_mount_path }}/torrents/config/blocklists/bt_blocklists"
  args:
    creates: "{{ usb_disk_mount_path }}/torrents/config/blocklists/bt_blocklists"
  tags:
    - skip_ansible_lint

- name: Set proper permissions for block list
  ansible.builtin.file:
    path: "{{ usb_disk_mount_path }}/torrents/config/blocklists/bt_blocklists"
    owner: transmission
    group: transmission
    mode: u=rw,g=r,o=r

- name: Create Luci ACL for Homepage OpenWRT widget
  ansible.builtin.copy:
    dest: /usr/share/rpcd/acl.d/homepage.json
    src: files/{{ inventory_hostname }}/usr/share/rpcd/acl.d/homepage.json
    mode: u=rw,g=r,o=r

- name: Allow Homepage OpenWRT widget to access Luci via RPC
  ansible.builtin.template:
    dest: /etc/config/rpcd
    src: files/{{ inventory_hostname }}/etc/config/rpcd.j2
    mode: u=rw,g=r,o=r
  no_log: true

- name: Configure samba4
  ansible.builtin.template:
    dest: /etc/config/samba4
    src: files/{{ inventory_hostname }}/etc/config/samba4.j2
    mode: u=rw,g=,o=
