- name: Configure attached block device {{ usb_disk_device }}
  ansible.builtin.template:
    dest: /etc/config/fstab
    src: files/{{ inventory_hostname }}/etc/config/fstab.j2
    mode: u=rw,g=r,o=r

- name: Create directory {{ usb_disk_mount_path }}
  ansible.builtin.file:
    path: "{{ usb_disk_mount_path }}"
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Check the mounted disks
  ansible.builtin.command: cat /proc/mounts
  changed_when: false
  register: mount_output

- name: Create file usb_disk_mount_path/USB_DISK_NOT_PRESENT if usb_disk_device_1 is not mounted
  ansible.builtin.file:
    path: "{{ usb_disk_mount_path }}/USB_DISK_NOT_PRESENT"
    state: touch
    mode: u=rw,g=r,o=r
  when: mount_output.stdout is not search('/dev/' + usb_disk_device + '1 ' + usb_disk_mount_path )

- name: Mount USB disk
  ansible.builtin.command: /sbin/block mount
  register: block_mount
  changed_when: block_mount.stdout is not search('/dev/' + usb_disk_device + '1 is already mounted')
  when: mount_output.stdout is not search('/dev/' + usb_disk_device + '1 ' + usb_disk_mount_path )

############################################
# Samba
############################################

- name: Configure Samba (/etc/config/samba)
  ansible.builtin.template:
    dest: /etc/config/samba
    src: files/{{ inventory_hostname }}/etc/config/samba.j2
    mode: u=rw,g=r,o=r

- name: Create local credential file for smaba
  delegate_to: localhost
  ansible.builtin.copy:
    dest: "{{ lookup('env', 'HOME') }}/Documents/secrets/{{ inventory_hostname }}-cifs-credentials"
    content: |
      [{{ inventory_hostname }}]
      username=root
      password={{ samba_root_password }}
    mode: u=rw,g=,o=
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"

- name: Set SMB password for root
  ansible.builtin.shell: |
    set -o pipefail
    echo -e "{{ samba_root_password }}\n{{ samba_root_password }}" | smbpasswd -a -s root
  changed_when: false

- name: Allow root to use samba
  ansible.builtin.replace:
    path: /etc/samba/smb.conf.template
    regexp: "^(\\s)invalid users = root"
    replace: "\\1# invalid users = root"

############################################
# Transmission
############################################

- name: Create directories for torrents
  ansible.builtin.file:
    path: "{{ usb_disk_mount_path }}/torrents/{{ item }}"
    state: directory
    owner: transmission
    group: transmission
    mode: u=rwx,g=rx,o=rx
  loop:
    - config
    - torrents
    - torrents-completed
    - torrents-incomplete

- name: Configure transmission
  ansible.builtin.template:
    dest: /etc/config/transmission
    src: files/{{ inventory_hostname }}/etc/config/transmission.j2
    mode: u=rw,g=r,o=r

- name: Install transmission torrent done smtp notification script
  ansible.builtin.template:
    dest: /etc/torrent-done.sh
    src: files/{{ inventory_hostname }}/etc/torrent-done.sh.j2
    mode: u=rwx,g=rx,o=rx

- name: Create /www/torrents directory
  ansible.builtin.file:
    path: /www/torrents
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Allow access to torrents-completed and torrents using http (uhttpd)
  ansible.builtin.file:
    src: "{{ usb_disk_mount_path }}/{{ item }}"
    dest: /www/{{ item }}
    state: link
    force: true
    mode: u=rwx,g=rx,o=rx
  loop:
    - torrents/torrents-completed
    - torrents/torrents

- name: Configure collectd_df
  ansible.builtin.shell: |
    uci set luci_statistics.collectd_df.enable=1 &&
    uci set luci_statistics.collectd_df.Devices=/dev/{{ usb_disk_device }}1 &&
    uci set luci_statistics.collectd_df.MountPoints={{ usb_disk_mount_path }} &&
    uci set luci_statistics.collectd_df.FSTypes=ext4
  changed_when: false

- name: Configure collectd_disk
  ansible.builtin.shell: |
    uci set luci_statistics.collectd_disk.enable=1 &&
    uci set luci_statistics.collectd_disk.Disks={{ usb_disk_device }}
  changed_when: false

- name: Enable hd-idle
  ansible.builtin.command: |
    uci set hd-idle.@hd-idle[-1].enabled=1
  changed_when: false

- name: Download MC config file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ruzickap/ansible-role-my_common_defaults/master/files/etc/skel/.config/mc/ini
    dest: /etc/mc/ini
    mode: u=rw,g=r,o=r

- name: Configure MC to run without mouse (/etc/profile.d/my-mc.sh)
  ansible.builtin.copy:
    dest: /etc/profile.d/my-mc.sh
    src: files/{{ inventory_hostname }}/etc/profile.d/my-mc.sh
    mode: u=rw,g=rx,o=rx

- name: Enable file highightning in mc
  ansible.builtin.get_url:
    url: https://raw.github.com/MidnightCommander/mc/master/misc/filehighlight.ini
    dest: /etc/mc/filehighlight.ini
    mode: u=rw,g=r,o=r

- name: Enable adblock
  ansible.builtin.command: |
    uci set adblock.global.adb_enabled=1
  changed_when: false

- name: Enable adblock lists
  ansible.builtin.command: |
    uci set adblock.{{ item }}.enabled=1
  loop: "{{ adblock_lists }}"
  changed_when: false

- name: Cronjob for adblock regular block list update
  ansible.builtin.cron:
    name: "Adblock regular block list update"
    minute: "0"
    hour: "4"
    job: "/etc/init.d/adblock reload"
