- name: Configure cloudflared
  ansible.builtin.shell: |
    uci set cloudflared.@cloudflared[0].enabled=1 &&
    uci set cloudflared.@cloudflared[0].token={{ cloudflare_api_key }} &&
    uci set cloudflared.@cloudflared[0].tag=fqdn={{ inventory_hostname }}
  changed_when: false

############################################
# Homepage
############################################

- name: Create Luci ACL for Homepage OpenWRT widget
  ansible.builtin.copy:
    dest: /usr/share/rpcd/acl.d/homepage.json
    src: files/{{ inventory_hostname }}/usr/share/rpcd/acl.d/homepage.json
    mode: u=rw,g=r,o=r

- name: Allow Homepage OpenWRT widget to access Luci via RPC
  ansible.builtin.template:
    dest: /etc/config/rpcd
    src: files/{{ inventory_hostname }}/etc/config/rpcd.j2
    mode: u=rw,g=r,o=r
  no_log: true

############################################
# vsftpd
############################################

- name: Configure vfsftpd (/etc/vsftpd.conf)
  community.general.ini_file:
    path: /etc/vsftpd.conf
    no_extra_spaces: true
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: u=rw,g=,o=
  loop:
    - option: anon_root
      value: "{{ usb_disk_mount_path }}/media/"
    - option: write_enable
      value: "NO"
    - option: anonymous_enable
      value: "YES"
    - option: syslog_enable
      value: "YES"
    - option: local_enable
      value: "NO"
    - option: hide_ids
      value: "YES"

- name: Chnage ftp user home directory
  ansible.builtin.replace:
    path: /etc/passwd
    regexp: "^ftp:\\*:55:55:ftp:/home/ftp:/bin/false"
    replace: "ftp:*:55:55:ftp:{{ usb_disk_mount_path }}/media:/bin/false"
  changed_when: false
