- name: Run all
  hosts: all
  gather_facts: false
  force_handlers: true
  vars:
    network_prefix: "{{ network_ip_subnet.split('/')[0].split('.')[:3] | join('.') }}"

  tasks:
    - name: Include tasks
      ansible.builtin.import_tasks: tasks/common.yml

    - name: Include specific tasks
      ansible.builtin.include_tasks: tasks/tasks_{{ inventory_hostname }}.yml

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yml
