- name: Run all
  hosts: all
  gather_facts: false

  tasks:
    - name: Include tasks
      ansible.builtin.import_tasks: tasks/common.yml

    - name: Include specific tasks
      ansible.builtin.include_tasks: tasks/tasks_{{ inventory_hostname }}.yml

    - name: UCI commit
      ansible.builtin.command: uci commit
      changed_when: false
