name: ansible-lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  ansible-playbooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v6.17.0
        with:
          targets: |
            main.yml
            playbooks/*.yml
